In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('data.csv')

In [3]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [4]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

In [6]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [7]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [11]:
#TAKING CARE OF MISSING DATA 


#from sklearn.preprocessing import Imputer
#imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [27]:
#ENCODING CATEGORICAL VALUES

#from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#labelencoder_X=LabelEncoder()
#labelencoder_X.fit_transform(X[:, 0])


array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [28]:
#X[:, 0]=labelencoder_X.fit_transform(X[:, 0])

In [29]:
#X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [34]:
#from sklearn.compose import ColumnTransformer
#ct=ColumnTransformer()
#ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')
#X = ct.fit_transform(X)
# Male/Female
#labelencoder_X = LabelEncoder()
#X[:, 2] = labelencoder_X.fit_transform(X[:, 2])

#onehotencoder=OneHotEncoder(categorical_features=[0])
#X=onehotencoder.fit_transform(X).toarray()

In [36]:
con=pd.get_dummies(dataset['Country'])
con.head(6)

France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
4       0        1      0
5       1        0      0

In [37]:
dataset=pd.concat([dataset,con],axis=1)
dataset.head(6)

Country   Age   Salary Purchased  France  Germany  Spain
0   France  44.0  72000.0        No       1        0      0
1    Spain  27.0  48000.0       Yes       0        0      1
2  Germany  30.0  54000.0        No       0        1      0
3    Spain  38.0  61000.0        No       0        0      1
4  Germany  40.0      NaN       Yes       0        1      0
5   France  35.0  58000.0       Yes       1        0      0

In [38]:
dataset.drop('Country',axis=1,inplace=True)

In [39]:
dataset.head(6)

Age   Salary Purchased  France  Germany  Spain
0  44.0  72000.0        No       1        0      0
1  27.0  48000.0       Yes       0        0      1
2  30.0  54000.0        No       0        1      0
3  38.0  61000.0        No       0        0      1
4  40.0      NaN       Yes       0        1      0
5  35.0  58000.0       Yes       1        0      0

In [42]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [44]:
X_test

array([[1, 30.0, 54000.0],
       [1, 50.0, 83000.0]], dtype=object)

In [45]:
y_test

array([0, 0], dtype=int64)

In [46]:
X_train

array([[1, 40.0, 63777.77777777778],
       [0, 37.0, 67000.0],
       [2, 27.0, 48000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [2, 38.0, 61000.0],
       [0, 44.0, 72000.0],
       [0, 35.0, 58000.0]], dtype=object)

In [47]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1], dtype=int64)

In [50]:
#FEATURE SCALING

from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [51]:
X_train

array([[ 0.13483997,  0.26306757,  0.12381479],
       [-0.94387981, -0.25350148,  0.46175632],
       [ 1.21355975, -1.97539832, -1.53093341],
       [ 1.21355975,  0.05261351, -1.11141978],
       [-0.94387981,  1.64058505,  1.7202972 ],
       [ 1.21355975, -0.0813118 , -0.16751412],
       [-0.94387981,  0.95182631,  0.98614835],
       [-0.94387981, -0.59788085, -0.48214934]])

In [53]:
X_test

array([[ 0.13483997, -1.45882927, -0.90166297],
       [ 0.13483997,  1.98496442,  2.13981082]])

In [ ]:



"""import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv('data.csv')
dataset.head()
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)"""


"""#FEATURE SCALING

from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)"""